# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='map',
            name='street',
            field=models.CharField(max_length=10, primary_key=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='EIN',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='legislation',
            table='legislation',
        ),
        migrations.AlterModelTable(
            name='map',
            table='map',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
