# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180204_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislation',
            name='city',
            field=models.CharField(default='none', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legislation',
            name='zipcode',
            field=models.CharField(default='none', max_length=5),
            preserve_default=False,
        ),
    ]
